// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvcayjlrwsqayrdtlkda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y2F5amxyd3NxYXlyZHRsa2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDE1NzUsImV4cCI6MjA1ODc3NzU3NX0.8HENFgn6EzL5iAANJ9KUO0uhhjJRHYUF7e40r7tK0Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);